# Run Tests

name: OpenMDAO Test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # latest versions
          - PY: 3
            NUMPY: 1
            SCIPY: 1
            PETSc: 3
            PYOPTSPARSE: 'v2.1.5'
          # baseline versions
          - PY: 3.8
            NUMPY: 1.18
            SCIPY: 1.4
            PETSc: 3.12
            PYOPTSPARSE: 'v2.1.5'
          # oldest supported versions
          - PY: 3.6
            NUMPY: 1.16
            SCIPY: 1.2
            PETSc: 3.10.2
            PYOPTSPARSE: 'v1.2'

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow --tags

      - uses: actions/setup-python@v2
        with:
          python-version:  ${{ matrix.PY }}

      - name: Install & test
        run: |
          echo "=============================================================";
          echo "Create conda environment";
          echo "=============================================================";
          source $CONDA/etc/profile.d/conda.sh;

          echo $CONDA/bin >> $GITHUB_PATH;

          conda create -n OpenMDAO python=${{ matrix.PY }} numpy=${{ matrix.NUMPY }} scipy=${{ matrix.SCIPY }} -q -y;

          conda activate OpenMDAO;

          if [ "${{ matrix.PETSc }}" ]; then
            echo "=============================================================";
            echo "Installing PETSc";
            echo "=============================================================";

            conda install -c anaconda mpi4py -q -y;
            conda install -c conda-forge petsc=${{ matrix.PETSc }} petsc4py -q -y;
          fi

          if [ "${{ matrix.PYOPTSPARSE }}" ]; then
            echo "=============================================================";
            echo "Installing pyoptsparse";
            echo "=============================================================";
            git clone -q https://github.com/OpenMDAO/build_pyoptsparse;

            cd build_pyoptsparse;
            chmod 755 ./build_pyoptsparse.sh;
            ./build_pyoptsparse.sh -b "${{ matrix.PYOPTSPARSE }}";
            cd ..

            export LD_LIBRARY_PATH=$HOME/ipopt/lib;
          fi

          echo "=============================================================";
          echo "Installing OpenMDAO";
          echo "=============================================================";
          pip install .[all];

          echo "=============================================================";
          echo "Installing optional packages for testing/coverage";
          echo "=============================================================";
          pip install psutil objgraph git+https://github.com/mdolab/pyxdsm;
          pyppeteer-install;

          echo "=============================================================";
          echo "Test environment";
          echo "=============================================================";
          conda list;

          echo "=============================================================";
          echo "Run tests & make docs";
          echo "=============================================================";
          cd openmdao/docs;

          testflo -n 1 openmdao --timeout=120 --show_skipped --coverage --coverpkg openmdao --cover-omit \*tests/\*  --cover-omit \*devtools/\* --cover-omit \*test_suite/\* --cover-omit \*docs/\* --cover-omit \*code_review/\*;
          
          if [ "${{ matrix.PETSc }}" ]; then
            make all;
          fi
